package examples

// sampleGoAppFiles holds the deterministic file content for the
// fixture. Keys are paths relative to the fixture root. Values are
// fixed strings — generation must produce byte-identical output across
// runs so users can diff against a known baseline.
//
// The calculator intentionally does not handle division by zero: that
// is the "obvious test improvement opportunity" agents are expected to
// notice when run against this fixture. The existing tests pass; new
// tests should be added to expose the missing edge case before
// changing the implementation.
var sampleGoAppFiles = map[string]string{
	".awo-fixture": awoFixtureMarker,
	"README.md":    sampleReadme,
	"go.mod":       sampleGoMod,
	".gitignore":   sampleGitignore,

	"calculator.go":      sampleCalculatorGo,
	"calculator_test.go": sampleCalculatorTestGo,
}

const awoFixtureMarker = `This directory is an AWO fixture. AWO will refuse to overwrite it
without --force, and will refuse to delete any directory at this path
that does not contain this marker file.
`

const sampleReadme = "# sample-go-app\n\n" +
	"A tiny Go module used as a **safe demo environment** for AWO.\n\n" +
	"This directory is its own git repository, separate from the host\n" +
	"repository AWO was invoked from. Anything AWO does inside\n" +
	"`.awo/fixtures/sample-go-app` stays inside `.awo/fixtures/sample-go-app`.\n\n" +
	"## Why this exists\n\n" +
	"You can dogfood AWO end-to-end (single, writer-reviewer, competitive\n" +
	"modes) against this fixture without risking changes to your real\n" +
	"codebase. Run AWO from inside this directory and any worktrees,\n" +
	"branches, or commits AWO produces only affect this fixture's git\n" +
	"history.\n\n" +
	"## Try it\n\n" +
	"```sh\n" +
	"cd .awo/fixtures/sample-go-app\n" +
	"\n" +
	"# Initialize AWO scaffolding inside the fixture itself.\n" +
	"awo init\n" +
	"\n" +
	"# Confirm the existing tests already pass before any agent runs.\n" +
	"go test ./...\n" +
	"\n" +
	"# Run a competitive race between Claude and Codex on a real task.\n" +
	"awo run \"add tests for the calculator edge cases\" \\\n" +
	"  --mode competitive \\\n" +
	"  --competitors claude,codex \\\n" +
	"  --verify \"go test ./...\"\n" +
	"```\n\n" +
	"## Known weak spot (intentional)\n\n" +
	"`Divide` panics on a zero divisor. The existing test file does not\n" +
	"exercise that case. A good agent task here is *\"add tests for the\n" +
	"calculator edge cases\"* — agents should write a failing test that\n" +
	"surfaces the panic, then either propose returning an error or\n" +
	"document the panic explicitly.\n\n" +
	"## Safety\n\n" +
	"- This fixture is regenerated by `awo examples create-fixture`.\n" +
	"- Existing fixtures are never overwritten without `--force`.\n" +
	"- AWO refuses to delete directories at this path that lack the\n" +
	"  `.awo-fixture` marker file, so unrelated content can never be\n" +
	"  destroyed by a fixture refresh.\n"

const sampleGoMod = `module awo.local/sample-go-app

go 1.22
`

const sampleGitignore = `# Build outputs
/bin/
/dist/

# Local AWO state created if you run "awo init" inside the fixture.
.awo/runs/
.awo/worktrees/
`

const sampleCalculatorGo = `// Package calculator is a tiny pure-arithmetic helper used as the
// AWO sample fixture. It is intentionally simple so dogfooding runs
// stay fast and deterministic.
package calculator

// Add returns a + b.
func Add(a, b int) int { return a + b }

// Sub returns a - b.
func Sub(a, b int) int { return a - b }

// Mul returns a * b.
func Mul(a, b int) int { return a * b }

// Divide returns a / b. It panics when b == 0; that is an
// intentional edge case the AWO sample task asks agents to expose
// with a test before fixing.
func Divide(a, b int) int {
	return a / b
}
`

const sampleCalculatorTestGo = `package calculator

import "testing"

func TestAdd(t *testing.T) {
	if got := Add(2, 3); got != 5 {
		t.Errorf("Add(2,3)=%d want 5", got)
	}
}

func TestSub(t *testing.T) {
	if got := Sub(10, 4); got != 6 {
		t.Errorf("Sub(10,4)=%d want 6", got)
	}
}

func TestMul(t *testing.T) {
	if got := Mul(6, 7); got != 42 {
		t.Errorf("Mul(6,7)=%d want 42", got)
	}
}

func TestDivideHappy(t *testing.T) {
	if got := Divide(10, 2); got != 5 {
		t.Errorf("Divide(10,2)=%d want 5", got)
	}
}

// NOTE: Divide(_, 0) is intentionally not tested here. The AWO demo
// task is to add edge-case coverage that exposes the missing
// behavior.
`
